### ISSUE TITLE
Expose metadata related to datacite managed data

### ISSUE THREAD

**Issue by physikerwelt** [MaRDI4NFDI/python-zbMathRest2Oai#9]
### Overall GOAL
Expose zbMATH Open Metadata related to DataCite-managed data in a standardized format.

### zbMATH Open Metadata
Under zbMATH Open Metadata, we understand zbMATH curated identifiers for ([documents](https://www.wikidata.org/wiki/Property:P894), [person](https://www.wikidata.org/wiki/Property:P1556), and [software](https://www.wikidata.org/wiki/Property:P6830)) as well as subject classification information for example expressed in the [MSC](https://www.wikidata.org/wiki/Property:P3285) and other information that can be encoded in the [datacite metadata format](http://schema.datacite.org/meta/kernel-4.4/).

###  DataCite-managed data
Datacite-managed data is data that has a DOI issued by DataCite. Note, this can be checked via [doi.org](https://doi.org/ra/10.5438/sjx9-hb16) even for [doi-ranges](https://doi.org/ra/10.5438).

###  Standardized format

This needs to be determined. One option is OAI-PMH in data-cite format.

* One option to reduce the amount of data that needs to be harvested by DataCite is to create a tag that only exposes the relevant fraction of data.

* Another option is a format DataCite format for this use case.

## Open questions

- [ ] How to determine if data is related to DataCite-managed data. For **first-order relations**, this is easy to decide on, for example, if a zbMATH Open is linked to an arXiv article that has a DataCite-issued DOI. It is more difficult, if, for example, an author has both zbMATH author ID and orcid, but the orcid is not used in the arXiv article of the author, but another datacite item that is not linked from zbMATH Open.

## Tasks

- [ ] Make a collection of example data
- [ ] Define a name for the tag in the OAI-PMH API
